image: continuumio/miniconda3

ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - before: |
      export FLASK_APP=app
      export FLASK_ENV=development
    init: |
      conda create --file environment.yaml
    command: |
      flask run

vscode:
  extensions:
    - ms-python.python
